CREATE DATABASE IF NOT EXISTS java_studio CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE java_studio;
CREATE TABLE IF NOT EXISTS users (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS projects (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 user_id BIGINT NOT NULL,
 name VARCHAR(150) NOT NULL,
 project_type VARCHAR(40) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_project_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS files (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 project_id BIGINT NOT NULL,
 path VARCHAR(500) NOT NULL,
 file_type VARCHAR(30) NOT NULL,
 content LONGTEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_project_path (project_id, path),
 CONSTRAINT fk_file_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS execution_history (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 user_id BIGINT,
 file_id BIGINT,
 language VARCHAR(30) NOT NULL,
 status VARCHAR(30) NOT NULL,
 output LONGTEXT,
 error_text LONGTEXT,
 executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_exec_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
 CONSTRAINT fk_exec_file FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE SET NULL
);
